services:
  # web:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   volumes:
  #     - ../src:/app/src
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DEBUG=1
  #     - SECRET_KEY=your-secret-key-here
  #     - DJANGO_SETTINGS_MODULE=budgenus.settings.dev
  #     - DB_NAME=budgenus_postgres
  #     - DB_USER=budgenus
  #     - DB_PASSWORD=budgenus
  #     - DB_HOST=localhost
  #     - DB_PORT=5432
  #   depends_on:
  #     - db
  #   command: >
  #     sh -c "python src/manage.py migrate &&
  #            python src/manage.py runserver 0.0.0.0:8000"
  # app:
  #   image: budgenus-image
  #   container_name: budgenus-back
  #   ports:
  #     - "8001:8000"
  #   volumes:
  #     - ../src:/app/src

  db:
    image: postgres
    container_name: budgenus-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=budgenus-postgres
      - POSTGRES_USER=budgenus
      - POSTGRES_PASSWORD=budgenus
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@budgenus.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: